import { createContext, useContext, useState, useCallback } from 'react'

export type Lang = 'en' | 'am'

interface LangContextType {
  lang: Lang
  setLang: (l: Lang) => void
  t: (key: string) => string
}

const LangContext = createContext<LangContextType>({
  lang: 'en',
  setLang: () => {},
  t: (key) => key,
})

export function LangProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem('askmian-lang') as Lang
    return saved === 'am' ? 'am' : 'en'
  })

  const setLang = useCallback((l: Lang) => {
    localStorage.setItem('askmian-lang', l)
    setLangState(l)
    document.documentElement.lang = l === 'am' ? 'am' : 'en'
  }, [])

  const t = useCallback(
    (key: string) => {
      const dict = DICT[lang]
      return dict[key] ?? DICT.en[key] ?? key
    },
    [lang]
  )

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  )
}

export const useLang = () => useContext(LangContext)

export const DICT: Record<Lang, Record<string, string>> = {
  en: {
    // Nav
    nav_home: 'Home',
    nav_services: 'Services',
    nav_apply: 'Apply',
    nav_how: 'How It Works',
    nav_faq: 'FAQ',
    nav_contact: 'Contact',
    nav_admin: 'Admin',

    // Hero
    hero_tag: 'UAE Visa & PRO Services',
    hero_title: 'Your Gateway to the UAE',
    hero_subtitle: 'Fast and reliable UAE visa processing and professional PRO services.',
    hero_cta_apply: 'Apply Now',
    hero_cta_whatsapp: 'WhatsApp Us',
    hero_30day: '30 Day Visa',
    hero_60day: '60 Day Visa',
    hero_ext: 'Visa Extension',
    hero_pro: 'PRO Services',

    // Why Choose Us
    wcu_tag: 'Why Choose Us',
    wcu_title: 'Trusted by Thousands',
    wcu_subtitle: 'We make UAE visa and PRO services simple, fast, and transparent.',
    wcu_speed_title: 'Fast Processing',
    wcu_speed_desc: '5 business days average. Urgent same-day service available.',
    wcu_transparent_title: 'Transparent Pricing',
    wcu_transparent_desc: 'No hidden fees. Clear pricing upfront before you apply.',
    wcu_secure_title: 'Secure & Reliable',
    wcu_secure_desc: 'Your documents and data are handled with strict confidentiality.',
    wcu_support_title: 'UAE-Based Support',
    wcu_support_desc: 'Local team in Abu Dhabi. Speak to a real person anytime.',

    // Services
    svc_tag: 'Visa Services',
    svc_title: 'Visit Visas & Extensions',
    svc_subtitle: 'Choose the visa type that fits your travel plans. All processed within 5 business days.',
    svc_30_title: '30-Day Visit Visa',
    svc_30_price: 'AED 1,200',
    svc_30_time: '5 business days',
    svc_30_req1: 'Passport Copy',
    svc_30_req2: 'Passport Photo',
    svc_30_req3: 'Bank Statement',
    svc_60_title: '60-Day Visit Visa',
    svc_60_price: 'AED 1,800',
    svc_60_time: '5 business days',
    svc_60_req1: 'Passport Copy',
    svc_60_req2: 'Passport Photo',
    svc_60_req3: 'Bank Statement',
    svc_ext_title: 'Visa Extension',
    svc_ext_price: 'AED 1,100',
    svc_ext_time: '5 business days',
    svc_ext_req1: 'Current Visa Copy',
    svc_ext_req2: 'Passport Copy',
    svc_change_title: 'Inside Country Status Change',
    svc_change_price: 'Price on Request',
    svc_change_time: '5 business days',
    svc_change_req1: 'Passport Copy',
    svc_change_req2: 'Current Visa Copy',
    svc_popular: 'POPULAR',
    svc_apply: 'Apply Now',

    // CTA
    cta_title: 'Ready to Start Your UAE Journey?',
    cta_subtitle: 'Apply now, upload your documents, and receive your visa within 5 business days. Partial refund available if visa is rejected.',
    cta_apply: 'Apply Now',
    cta_whatsapp: 'WhatsApp Us',

    // PRO Services
    pro_tag: 'PRO Services',
    pro_title: 'Professional Government Services',
    pro_subtitle: 'End-to-end business and government documentation support in the UAE.',
    pro_biz_title: 'Business Setup',
    pro_biz_desc: 'Complete company formation services including mainland, free zone, and offshore setups.',
    pro_license_title: 'Trade License Renewals',
    pro_license_desc: 'Hassle-free renewal of your trade license with timely reminders.',
    pro_doc_title: 'Document Clearing',
    pro_doc_desc: 'Efficient document attestation, translation, and government approval.',
    pro_family_title: 'Family Visa Assistance',
    pro_family_desc: 'Complete family visa processing services.',
    pro_imm_title: 'Immigration Services',
    pro_imm_desc: 'Full immigration support including entry permits and residence visas.',
    pro_emirates_title: 'Emirates ID Assistance',
    pro_emirates_desc: 'Quick Emirates ID application, renewal, and replacement.',
    pro_contact: 'Contact Us',
    pro_price: 'for pricing',

    // How It Works
    hiw_tag: 'Simple Process',
    hiw_title: 'How It Works',
    hiw_subtitle: 'Four simple steps to get your UAE visa. Processing time: 5 business days.',
    hiw_step1_title: 'Upload Documents',
    hiw_step1_desc: 'Submit your passport copy, passport photo, and 6-month bank statement via WhatsApp or Telegram.',
    hiw_step2_title: 'Make Payment',
    hiw_step2_desc: 'Pay securely using card (Stripe), bank transfer, WhatsApp, or cash at our office.',
    hiw_step3_title: 'Processing & Verification',
    hiw_step3_desc: 'Our team reviews your documents and submits your application to immigration authorities.',
    hiw_step4_title: 'Receive Your Visa',
    hiw_step4_desc: 'Get your approved visa delivered directly to your email or WhatsApp within 5 business days.',

    // Testimonials
    test_tag: 'Client Stories',
    test_title: 'What Our Clients Say',
    test_role1: 'Business Consultant',
    test_text1: 'Ask Mian made my visa process incredibly smooth. I received my 60-day visa within 5 days.',
    test_role2: 'Entrepreneur',
    test_text2: 'The PRO services saved my business countless hours. Outstanding understanding of UAE regulations.',
    test_role3: 'Marketing Director',
    test_text3: 'I needed an urgent visa extension and Ask Mian delivered beyond expectations.',

    // FAQ
    faq_tag: 'Got Questions?',
    faq_title: 'Frequently Asked',
    faq_subtitle: 'Find answers to common questions about our visa and PRO services.',
    faq_q1: 'How long does visa processing take?',
    faq_a1: 'Standard visa processing takes 5 business days from the date we receive all required documents and payment. This allows time for document verification, application submission to immigration authorities, and approval processing.',
    faq_q2: 'What documents are required?',
    faq_a2: 'For a UAE visit visa, you need three documents: (1) A clear passport copy with minimum 6 months validity, (2) A passport-sized photograph with white background, and (3) A 6-month bank statement. Upload these via WhatsApp or our Telegram bot after submitting your application.',
    faq_q3: 'Can I extend my visa inside the UAE?',
    faq_a3: 'Yes, you can extend your visit visa while inside the UAE without leaving the country. We offer visa extension services starting from AED 1,100. We recommend starting the extension process at least 5 days before your current visa expires.',
    faq_q4: 'What happens if my visa is rejected?',
    faq_a4: 'In the rare event of a visa rejection, we will first analyze the reason and guide you on the best course of action. Depending on the rejection reason and processing stage, a partial refund may be issued.',
    faq_q5: 'Can I apply from inside the UAE?',
    faq_a5: 'Yes, you can apply for a new visa or extend your existing visa while inside the UAE. We offer inside-country status change services that allow you to switch visa types without leaving the country.',
    faq_q6: 'What payment methods do you accept?',
    faq_a6: 'We accept four payment methods: (1) Card payment via Stripe, (2) Bank transfer to our FAB account, (3) Cash payment at our Abu Dhabi office, and (4) Payment via WhatsApp.',
    faq_q7: 'Is there a refund policy?',
    faq_a7: 'Yes. If your visa application is rejected by immigration authorities, we offer a partial refund based on the processing stage. Refunds for bank transfers and card payments are processed within 7-14 business days.',
    faq_cta: 'Still have questions?',
    faq_cta_sub: 'Our team is here to help you.',
    faq_cta_btn: 'Chat on WhatsApp',

    // Contact Page
    ct_title: 'Contact Us',
    ct_subtitle: 'Have questions? We are here to help. Reach out via phone, WhatsApp, email, or visit our office.',
    ct_form_title: 'Send a Message',
    ct_name: 'Full Name',
    ct_email: 'Email Address',
    ct_phone: 'Phone / WhatsApp',
    ct_message: 'Your Message',
    ct_send: 'Send Message',
    ct_info_title: 'Contact Information',
    ct_address: 'Address',
    ct_address_val: 'Office on Appointment, Abu Dhabi, UAE',
    ct_hours: 'Working Hours',
    ct_hours_val: 'Mon - Fri: 9:00 AM - 9:00 PM',
    ct_phone_lbl: 'Phone',
    ct_email_lbl: 'Email',
    ct_license: 'Trade License',
    ct_whatsapp_btn: 'Chat on WhatsApp',
    ct_call_btn: 'Call Now',

    // Apply Page
    ap_tag: 'Visa Application',
    ap_title: 'Apply for UAE Visa',
    ap_subtitle: 'Complete the form below. Processing time: 5 business days',
    ap_step1: 'Personal Info',
    ap_step2: 'Documents',
    ap_step3: 'Payment',
    ap_step4: 'Review',
    ap_personal_title: 'Personal Information',
    ap_fullname: 'Full Name',
    ap_fullname_ph: 'As shown on passport',
    ap_nationality: 'Nationality',
    ap_nationality_ph: 'e.g. Ethiopian',
    ap_location: 'Current Location',
    ap_location_ph: 'e.g. Addis Ababa',
    ap_phone: 'Phone / WhatsApp',
    ap_phone_ph: '+971 55 868 9543',
    ap_email: 'Email Address',
    ap_email_ph: 'your@email.com',
    ap_visa_title: 'Visa Details',
    ap_visa_select: 'Select Visa Type',
    ap_travel_date: 'Expected Travel Date',
    ap_notes: 'Additional Notes',
    ap_notes_ph: 'Any special requirements or questions...',
    ap_docs_title: 'Required Documents',
    ap_docs_subtitle: 'Please upload the following 3 documents. Click or drag & drop.',
    ap_passport_lbl: 'Passport Copy (Data Page)',
    ap_passport_desc: 'Clear photo of your passport information page',
    ap_photo_lbl: 'Passport Size Photo',
    ap_photo_desc: 'White background, recent photograph',
    ap_bank_lbl: '6-Month Bank Statement',
    ap_bank_desc: 'PDF or clear photo of your bank statement',
    ap_docs_status: 'Documents Status',
    ap_docs_count: 'uploaded',
    ap_pay_title: 'Select Payment Method',
    ap_amount_due: 'Amount due',
    ap_pay_card: 'Pay with Card',
    ap_pay_card_desc: 'Secure payment via Stripe',
    ap_pay_bank: 'Bank Transfer',
    ap_pay_bank_desc: 'Transfer to our FAB account',
    ap_pay_whatsapp: 'Pay via WhatsApp',
    ap_pay_whatsapp_desc: 'Send payment details on WhatsApp',
    ap_pay_cash: 'Cash Payment',
    ap_pay_cash_desc: 'Visit our office in Abu Dhabi',
    ap_bank_details: 'Bank Transfer Details',
    ap_bank_name: 'Bank',
    ap_bank_name_val: 'First Abu Dhabi Bank (FAB)',
    ap_acct_name: 'Account Name',
    ap_acct_name_val: 'ASK MIAN LLC',
    ap_acct_num: 'Account Number',
    ap_acct_num_val: '1234567890',
    ap_iban: 'IBAN',
    ap_office_title: 'Office Address',
    ap_office_val1: 'Office on Appointment',
    ap_office_val2: 'Abu Dhabi, United Arab Emirates',
    ap_office_val3: 'Mon - Fri: 9:00 AM - 9:00 PM',
    ap_redirect_whatsapp: 'You will be redirected to WhatsApp to complete payment after submission.',
    ap_stripe_link: 'You will receive a secure payment link via WhatsApp after submission.',
    ap_review_title: 'Review Your Application',
    ap_important: 'Important Notice',
    ap_terms: 'By submitting, you confirm all information is accurate. Visa approval is subject to immigration authority decision. Partial refund available if visa is rejected.',
    ap_back: 'Back',
    ap_cancel: 'Cancel',
    ap_continue: 'Continue',
    ap_submit: 'Submit Application',
    ap_submitting: 'Submitting...',

    // Success
    ap_success_title: 'Application Submitted!',
    ap_success_thanks: 'Thank you',
    ap_success_appid: 'Your application ID is',
    ap_success_team: 'Our team will contact you within 24 hours.',
    ap_success_docs: 'Documents received',
    ap_success_payment: 'Payment method',
    ap_success_process: 'We process your visa within 5 business days',
    ap_success_receive: 'Receive your visa via email/WhatsApp',
    ap_new_app: 'New Application',

    // Footer
    ft_tagline: 'Fast & reliable UAE visa and PRO services.',
    ft_links: 'Quick Links',
    ft_contact: 'Contact',
    ft_rights: 'All rights reserved.',
    ft_trade: 'Trade License',

    // Admin
    ad_title: 'Admin Dashboard',
    ad_subtitle: 'Manage visa applications and payments',
    ad_total: 'Total Applications',
    ad_pending: 'Pending',
    ad_processing: 'Processing',
    ad_completed: 'Completed',
    ad_revenue: 'Revenue (AED)',
    ad_search: 'Search by name, phone, visa type...',
    ad_filter: 'Filter',
    ad_id: 'ID',
    ad_name: 'Name',
    ad_visa_type: 'Visa Type',
    ad_phone: 'Phone',
    ad_status: 'Status',
    ad_payment: 'Payment',
    ad_date: 'Date',
    ad_no_apps: 'No applications found',
    ad_loading: 'Loading applications...',
    ad_personal: 'Personal Information',
    ad_visa_payment: 'Visa & Payment',
    ad_documents: 'Documents',
    ad_notes: 'Notes',
    ad_contact_whatsapp: 'Contact on WhatsApp',
    ad_awaiting: 'Awaiting Transfer',
  },
  am: {
    // Nav
    nav_home: 'መነሻ',
    nav_services: 'አገልግሎቶች',
    nav_apply: 'ያመልክቱ',
    nav_how: 'እንዴት ይሰራል',
    nav_faq: 'ተደጋጋሚ ጥያቄዎች',
    nav_contact: 'ያግኙን',
    nav_admin: 'አስተዳዳሪ',

    // Hero
    hero_tag: 'የUAE ቪዛ እና PRO አገልግሎቶች',
    hero_title: 'ወደ UAE የሚወስድ በርዎ',
    hero_subtitle: 'ፈጣን እና አስተማማኝ የUAE ቪዛ ማስኬድ እና prefessional PRO አገልግሎቶች።',
    hero_cta_apply: 'አሁን ያመልክቱ',
    hero_cta_whatsapp: 'WhatsApp',
    hero_30day: '30 ቀን ቪዛ',
    hero_60day: '60 ቀን ቪዛ',
    hero_ext: 'የቪዛ ማራዘሚያ',
    hero_pro: 'PRO አገልግሎቶች',

    // Why Choose Us
    wcu_tag: 'ለምን እኛን ይመርጡ',
    wcu_title: 'በሺዎች የሚቆጠሩ ያምኑብናል',
    wcu_subtitle: 'የUAE ቪዛ እና PRO አገልግሎቶችን ቀላል፣ ፈጣን፣ እና ግልጽ እናደርጋለን።',
    wcu_speed_title: 'ፈጣን ማስኬድ',
    wcu_speed_desc: 'አማካይ 5 የንግድ ቀናት። አስቸኳይ አገልግሎት ይገኛል።',
    wcu_transparent_title: 'ግልጽ ዋጋ',
    wcu_transparent_desc: 'የተሸፈኑ ክፍያዎች የሉም። ከማመልከቻዎ በፊት ግልጽ ዋጋ።',
    wcu_secure_title: 'ደህና እና አስተማማኝ',
    wcu_secure_desc: 'ሰነዶችዎ እና መረጃዎ በጥብቅ ሚስጥራዊነት ይዘየራል።',
    wcu_support_title: 'በUAE ውስጥ ድጋፍ',
    wcu_support_desc: 'በአቡ ዳቢ የሚገኝ ቡድን። ከጭንቀል ሰው ጋር ይነጋገሩ።',

    // Services
    svc_tag: 'የቪዛ አገልግሎቶች',
    svc_title: 'የጉብኝት ቪዛ እና ማራዘሚያ',
    svc_subtitle: 'የጉዞ ዕቅድዎን የሚስማማውን የቪዛ አይነት ይምረጡ። ሁሉም በ5 የንግድ ቀናት ውስጥ ይሰራል።',
    svc_30_title: '30-ቀን የጉብኝት ቪዛ',
    svc_30_price: '1,200 ድርሀም',
    svc_30_time: '5 የንግድ ቀናት',
    svc_30_req1: 'የፓስፖርት ቅጂ',
    svc_30_req2: 'የፓስፖርት ፎቶ',
    svc_30_req3: 'የባንክ መግቢያ',
    svc_60_title: '60-ቀን የጉብኝት ቪዛ',
    svc_60_price: '1,800 ድርሀም',
    svc_60_time: '5 የንግድ ቀናት',
    svc_60_req1: 'የፓስፖርት ቅጂ',
    svc_60_req2: 'የፓስፖርት ፎቶ',
    svc_60_req3: 'የባንክ መግቢያ',
    svc_ext_title: 'የቪዛ ማራዘሚያ',
    svc_ext_price: '1,100 ድርሀም',
    svc_ext_time: '5 የንግድ ቀናት',
    svc_ext_req1: 'የአሁን ቪዛ ቅጂ',
    svc_ext_req2: 'የፓስፖርት ቅጂ',
    svc_change_title: 'ከውጭ ሳይወጡ ሁኔታ መቀየሪያ',
    svc_change_price: 'ዋጋ በመጠየቅ',
    svc_change_time: '5 የንግድ ቀናት',
    svc_change_req1: 'የፓስፖርት ቅጂ',
    svc_change_req2: 'የአሁን ቪዛ ቅጂ',
    svc_popular: 'ታዋቂ',
    svc_apply: 'አሁን ያመልክቱ',

    // CTA
    cta_title: 'የUAE ጉዞዎን ለማስጀመር ዝግጁ ነዎት?',
    cta_subtitle: 'አሁን ያመልክቱ፣ ሰነዶችዎን ያስገቡ፣ እና ቪዛዎን በ5 የንግድ ቀናት ውስጥ ይቀበሉ። ቪዛ ከተሰረዘ ከፊል መላ ምላሽ ይገኛል።',
    cta_apply: 'አሁን ያመልክቱ',
    cta_whatsapp: 'WhatsApp',

    // PRO Services
    pro_tag: 'PRO አገልግሎቶች',
    pro_title: ' prefessional የመንግስት አገልግሎቶች',
    pro_subtitle: 'በUAE ውስጥ መጨረሻ-ወደ-መጨረሻ ንግድ እና የመንግስት ሰነድ ድጋፍ።',
    pro_biz_title: 'የንግድ ማቋቋሚያ',
    pro_biz_desc: 'ሙሉ የኩባንያ ምስረታ አገልግሎቶች።',
    pro_license_title: 'የንግድ ፈቃድ ማደሻዎች',
    pro_license_desc: 'ያለችግር የንግድ ፈቃድ ማደስ።',
    pro_doc_title: 'የሰነድ ማጽዳት',
    pro_doc_desc: 'የሰነድ ማረጋገጫ፣ ትርጉም እና የመንግስት ማፅደቂያ።',
    pro_family_title: 'የቤተሰብ ቪዛ እገዛ',
    pro_family_desc: 'ሙሉ የቤተሰብ ቪዛ ማስኬጃ አገልግሎቶች።',
    pro_imm_title: 'የህዝብ ዝውውር አገልግሎቶች',
    pro_imm_desc: 'ሙሉ የህዝብ ዝውውር ድጋፍ።',
    pro_emirates_title: 'የኢሚራት መታወቂያ እገዛ',
    pro_emirates_desc: 'ፈጣን የኢሚራት መታወቂያ ማመልከቻ እና ማደስ።',
    pro_contact: 'ያግኙን',
    pro_price: 'ዋጋ',

    // How It Works
    hiw_tag: 'ቀላል ሂደት',
    hiw_title: 'እንዴት እንደሚሰራ',
    hiw_subtitle: 'የUAE ቪዛ ለማግኘት 4 ቀላል ደረጃዎች። ማስኬድ ጊዜ፡ 5 የንግድ ቀናት።',
    hiw_step1_title: 'ሰነዶችን ያስገቡ',
    hiw_step1_desc: 'ፓስፖርት ቅጂ፣ የፓስፖርት ፎቶ፣ እና የ6 ወር የባንክ መግቢያ በWhatsApp ወይም Telegram ያስገቡ።',
    hiw_step2_title: 'ክፍያ ያድርጉ',
    hiw_step2_desc: 'በካርድ (Stripe)፣ ባንክ ዝውውር፣ WhatsApp፣ ወይም ጥሬ ገንዘብ ይክፈሉ።',
    hiw_step3_title: 'ማስኬድ እና ማረጋገጫ',
    hiw_step3_desc: 'ቡድናችን ሰነዶችዎን ይመረምራል እና ወደ የህዝብ ዝውውር ባለሥልጣናት ያስገባል።',
    hiw_step4_title: 'ቪዛዎን ይቀበሉ',
    hiw_step4_desc: 'የጸደቀውን ቪዛ በ5 የንግድ ቀናት ውስጥ በኢሜል ወይም WhatsApp ይቀበሉ።',

    // Testimonials
    test_tag: 'የደንበኞች ታሪኮች',
    test_title: 'ደንበኞቻችን ምን ይላሉ',
    test_role1: 'የቢዝነስ አማካሪ',
    test_text1: 'Ask Mian የቪዛ ሂደቴን በጣም አስተማማኝ አደረገው። 60-ቀን ቪዛዬን በ5 ቀናት ተቀብያለሁ።',
    test_role2: 'የንግድ ባለቤት',
    test_text2: 'PRO አገልግሎቶች ንግዴን ብዙ ሰዓታት አዳኑት። የUAE ደንቦችን በጣም ያውቃሉ።',
    test_role3: 'የማርኬቲንግ ዳይሬክተር',
    test_text3: 'አስቸኳይ የቪዛ ማራዘሚያ ያስፈልገኝ ነበር እና Ask Mian በጣም ፈጣን አገልግሎት ሰጠ።',

    // FAQ
    faq_tag: 'ጥያቄ አለዎት?',
    faq_title: 'ብዙ ጊዜ የሚጠየቁ ጥያቄዎች',
    faq_subtitle: 'ስለ ቪዛ እና PRO አገልግሎቶቻችን ተደጋጋሚ ጥያቄዎችን ይመልከቱ።',
    faq_q1: 'የቪዛ ማስኬድ ምን ያህል ጊዜ ይወስዳል?',
    faq_a1: 'መደበኛ የቪዛ ማስኬድ 5 የንግድ ቀናት ይወስዳል። ይህ ለሰነድ ማረጋገጫ፣ ለማመልከቻ መስጫ፣ እና ለፍቃድ ሂደት ጊዜ ያስገድዳል።',
    faq_q2: 'የትኞች ሰነዶች ያስፈልጋሉ?',
    faq_a2: 'ለUAE የጉብኝት ቪዛ 3 ሰነዶች ያስፈልጋሉ፡ (1) ከ6 ወር በላይ ተረጋጋይነት ያለው የፓስፖርት ቅጂ፣ (2) ነጭ መነሻ ያለው የፓስፖርት መጠን ፎቶ፣ እና (3) የ6 ወር የባንክ መግቢያ።',
    faq_q3: 'ቪዛዬን ከUAE ውስጥ ማራዘም እችላለሁ?',
    faq_a3: 'አዎ! ከUAE ውጭ ሳይወጡ የቪዛ ማራዘሚያ አገልግሎት እንሰጣለን። የቪዛ ማራዘሚያ ከ1,100 ድርሀም ይጀምራል።',
    faq_q4: 'ቪዛዬ ቢሰረዝ ምን ይሆናል?',
    faq_a4: 'በጣም ውስን ዕድል ላይ ቪዛ ከተሰረዘ፣ ምክንያቱን እንተንስሳለን። ከማስኬድ ደረጃው በመነሳት ከፊል መላ ምላሽ ሊገኝ ይችላል።',
    faq_q5: 'ከUAE ውስጥ ማመልከት እችላለሁ?',
    faq_a5: 'አዎ! ከሀገር ውስጥ ሳይወጡ ሁኔታ መቀየሪያ አገልግሎቶችን እንሰጣለን።',
    faq_q6: 'የትኞች የክፍያ ዘዴዎችን ተቀብለዋል?',
    faq_a6: '4 የክፍያ ዘዴዎችን ተቀብለናል፡ (1) በካርድ (Stripe)፣ (2) ባንክ ዝውውር፣ (3) ጥሬ ገንዘብ፣ እና (4) WhatsApp።',
    faq_q7: 'የመላ ምላሽ ድንጋጌ አለ?',
    faq_a7: 'አዎ። ቪዛ ማመልከቻ ከተሰረዘ ከፊል መላ ምላሽ ይገኛል። ለባንክ ዝውውር እና ካርድ ክፍያዎች መላ ምላሽ በ7-14 የንግድ ቀናት ውስጥ ይሰራል።',
    faq_cta: 'ጥያቄ አለዎት?',
    faq_cta_sub: 'ቡድናችን ለመርዳት ዝግጁ ነው።',
    faq_cta_btn: 'በWhatsApp ይነጋገሩ',

    // Contact Page
    ct_title: 'ያግኙን',
    ct_subtitle: 'ጥያቄ አለዎት? እኛ እዚህ ጋር ነን። በስልክ፣ WhatsApp፣ ኢሜል፣ ወይም ቢሮዋችንን ይጎብኙ።',
    ct_form_title: 'መልእክት ይላኩ',
    ct_name: 'ሙሉ ስም',
    ct_email: 'ኢሜል አድራሻ',
    ct_phone: 'ስልክ / WhatsApp',
    ct_message: 'መልእክትዎ',
    ct_send: 'መልእክት ይላኩ',
    ct_info_title: 'የእኛ ማግኛ መረጃ',
    ct_address: 'አድራሻ',
    ct_address_val: 'በቀጠሮ፣ አቡ ዳቢ፣ UAE',
    ct_hours: 'የስራ ሰዓታት',
    ct_hours_val: 'ሰኞ - አርብ፦ 9:00 ጠዋት - 9:00 ማታ',
    ct_phone_lbl: 'ስልክ',
    ct_email_lbl: 'ኢሜል',
    ct_license: 'የንግድ ፈቃድ',
    ct_whatsapp_btn: 'በWhatsApp ይነጋገሩ',
    ct_call_btn: 'አሁን ይደውሉ',

    // Apply Page
    ap_tag: 'የቪዛ ማመልከቻ',
    ap_title: 'ለUAE ቪዛ ያመልክቱ',
    ap_subtitle: 'ከዚህ በታች ያለውን ቅጽ ይሙሉ። የማስኬድ ጊዜ፡ 5 የንግድ ቀናት',
    ap_step1: 'የግል መረጃ',
    ap_step2: 'ሰነዶች',
    ap_step3: 'ክፍያ',
    ap_step4: 'ምርመራ',
    ap_personal_title: 'የግል መረጃ',
    ap_fullname: 'ሙሉ ስም',
    ap_fullname_ph: 'እንደ ፓስፖርት ላይ የሚታየው',
    ap_nationality: 'ዜግነት',
    ap_nationality_ph: 'ለምሳሌ፦ ኢትዮጵያዊ',
    ap_location: 'አሁን የሚገኙበት ቦታ',
    ap_location_ph: 'ለምሳሌ፦ አዲስ አበባ',
    ap_phone: 'ስልክ / WhatsApp',
    ap_phone_ph: '+971 55 868 9543',
    ap_email: 'ኢሜል አድራሻ',
    ap_email_ph: 'your@email.com',
    ap_visa_title: 'የቪዛ ዝርዝር',
    ap_visa_select: 'የቪዛ አይነት ይምረጡ',
    ap_travel_date: 'የሚጠብቁት የጉዞ ቀን',
    ap_notes: 'ተጨማሪ ማስታወሻ',
    ap_notes_ph: 'ማንኛውም ልዩ ፍላጎት ወይም ጥያቄ...',
    ap_docs_title: 'አስፈላጊ ሰነዶች',
    ap_docs_subtitle: 'ከዚህ በታች ያሉትን 3 ሰነዶች ያስገቡ። ጠቅ ያድርጉ ወይም ይጎትቱ።',
    ap_passport_lbl: 'የፓስፖርት ቅጂ (ዋና ገጽ)',
    ap_passport_desc: 'የፓስፖርት መረጃ ገጽዎን ግልፅ ፎቶ ያስገቡ',
    ap_photo_lbl: 'የፓስፖርት መጠን ፎቶ',
    ap_photo_desc: 'ነጭ መነሻ፣ በቅርብ የተወሰደ ፎቶ',
    ap_bank_lbl: 'የ6 ወር የባንክ መግቢያ',
    ap_bank_desc: 'PDF ወይም የባንክ መግቢያዎ ግልፅ ፎቶ',
    ap_docs_status: 'የሰነዶች ሁኔታ',
    ap_docs_count: 'የተላኩ',
    ap_pay_title: 'የክፍያ ዘዴ ይምረጡ',
    ap_amount_due: 'የሚከፈል ገንዘብ',
    ap_pay_card: 'በካርድ ይክፈሉ',
    ap_pay_card_desc: 'በStripe ደህና ክፍያ',
    ap_pay_bank: 'ባንክ ዝውውር',
    ap_pay_bank_desc: 'ወደ FAB መለያችን ያስተላልፉ',
    ap_pay_whatsapp: 'በWhatsApp ይክፈሉ',
    ap_pay_whatsapp_desc: 'WhatsApp ላይ የክፍያ ዝርዝር ይላኩ',
    ap_pay_cash: 'ጥሬ ገንዘብ',
    ap_pay_cash_desc: 'ቢሮአችን በአቡ ዳቢ ይጎብኙ',
    ap_bank_details: 'የባንክ ዝውውር ዝርዝር',
    ap_bank_name: 'ባንክ',
    ap_bank_name_val: 'ፋርስት አቡ ዳቢ ባንክ (FAB)',
    ap_acct_name: 'መለያ ስም',
    ap_acct_name_val: 'ASK MIAN LLC',
    ap_acct_num: 'መለያ ቁጥር',
    ap_acct_num_val: '1234567890',
    ap_iban: 'IBAN',
    ap_office_title: 'የቢሮ አድራሻ',
    ap_office_val1: 'በቀጠሮ',
    ap_office_val2: 'አቡ ዳቢ፣ የተባበሩት ዓረብ ኤምሬትስ',
    ap_office_val3: 'ሰኞ - አርብ፦ 9:00 ጠዋት - 9:00 ማታ',
    ap_redirect_whatsapp: 'ክፍያዎን ለማጠናቀቅ ከምርመራ በኋላ ወደ WhatsApp ይመራዎታል።',
    ap_stripe_link: 'የደህና የክፍያ ማስፈንጠሪያ ከምርመራ በኋላ በWhatsApp ይደርስዎታል።',
    ap_review_title: 'ማመልከቻዎን ይመልከቱ',
    ap_important: 'አስፈላጊ ማስታወሻ',
    ap_terms: 'በማስገባት፣ ሁሉም መረጃዎች ትክክለኛ እንደሆነ ያረጋግጣሉ። የቪዛ ፍቃድ የህዝብ ዝውውር ባለሥልጣናትን ይወሳል። ቪዛ ከተሰረዘ ከፊል መላ ምላሽ ይገኛል።',
    ap_back: 'ተመለስ',
    ap_cancel: 'ይቅር',
    ap_continue: 'ቀጥል',
    ap_submit: 'ማመልከቻ ያስገቡ',
    ap_submitting: 'እየተላከ ነው...',

    // Success
    ap_success_title: 'ማመልከቻ ተሳክቷል!',
    ap_success_thanks: 'አመሰግናለን',
    ap_success_appid: 'የማመልከቻ ቁጥርዎ',
    ap_success_team: 'ቡድናችን በ24 ሰዓታት ውስጥ እናገኝዎታለን።',
    ap_success_docs: 'የተቀበልነው ሰነዶች',
    ap_success_payment: 'የክፍያ ዘዴ',
    ap_success_process: 'ቪዛዎን በ5 የንግድ ቀናት ውስጥ እናስኬዳለን',
    ap_success_receive: 'ቪዛዎን በኢሜል/WhatsApp ይቀበሉ',
    ap_new_app: 'አዲስ ማመልከቻ',

    // Footer
    ft_tagline: 'ፈጣን እና አስተማማኝ የUAE ቪዛ እና PRO አገልግሎቶች።',
    ft_links: 'ፈጣን ማገናኛዎች',
    ft_contact: 'አግኙን',
    ft_rights: 'መብት በሙሉ የተጠበቀ ነው።',
    ft_trade: 'የንግድ ፈቃድ',

    // Admin
    ad_title: 'የአስተዳዳሪ ዳሽቦርድ',
    ad_subtitle: 'የቪዛ ማመልከቾችን እና ክፍያዎችን ያስተዳድሩ',
    ad_total: 'ጠቅላላ ማመልከቾች',
    ad_pending: 'በመጠባበቅ ላይ',
    ad_processing: 'በማስኬድ ላይ',
    ad_completed: 'የተጠናቀቁ',
    ad_revenue: 'ገቢ (ድርሀም)',
    ad_search: 'በስም፣ ስልክ፣ የቪዛ አይነት ይፈልጉ...',
    ad_filter: 'ማጣሪያ',
    ad_id: 'ቁጥር',
    ad_name: 'ስም',
    ad_visa_type: 'የቪዛ አይነት',
    ad_phone: 'ስልክ',
    ad_status: 'ሁኔታ',
    ad_payment: 'ክፍያ',
    ad_date: 'ቀን',
    ad_no_apps: 'ምንም ማመልከቾች አልተገኙም',
    ad_loading: 'ማመልከቾችን እየጫኑ ነው...',
    ad_personal: 'የግል መረጃ',
    ad_visa_payment: 'ቪዛ እና ክፍያ',
    ad_documents: 'ሰነዶች',
    ad_notes: 'ማስታወሻ',
    ad_contact_whatsapp: 'በWhatsApp ይነጋገሩ',
    ad_awaiting: 'ዝውውሩን በመጠባበቅ ላይ',
  },
}
